export let storesList = [
	{
		'store-id': 'eko-maluch',
		'store-name': 'Eko Maluch',
		'store-src': 'eko-maluch.png',
		'store-brands': [ 'anavy', 'kokosi', 'lbd', 'puppi', 'magabi', 'disana', 'za-maszyna', 'magabi', 'zufizo', 'green-pieluszki', 'fomi', 'anna-luna', 'doodush', 'rasppies', 'timi', 'tulipoopka', 'bambino-mio' ],
		'store-url': 'https://www.ekomaluch.pl/',
	},
	{
		'store-id': 'chmurka-biala',
		'store-name': 'Chmurka Biała',
		'store-src': 'chmurka-biala.png',
		'store-brands': [ 'kokosi', 'lbd', 'puppi', 'pupus', 'xkko', 'jellyfish', 'green-pieluszki', 'zufizo', 'rasppies', 'timi', 'tulipoopka', 'bambino-mio', 'latki-dwie', 'anavy', 'baby-lemur', 'funky-monkey', 'little-rhino' ],
		'store-url': 'https://chmurkabiala.pl/',
	},
	{
		'store-id': 'better-land',
		'store-name': 'Better Land',
		'store-src': 'better-land.jpeg',
		'store-brands': [ 'anavy', 'sue-and-sophie', 'kokosi', 'lbd', 'puppi', 'magabi', 'disana', 'za-maszyna', 'magabi', 'zufizo', 'green-pieluszki', 'pupus', 'xkko', 'jellyfish', 'green-pieluszki', 'zufizo', 'baby-lemur', 'funky-monkey', 'little-rhino', 'fomi', 'anna-luna', 'funky-monkey',],
		'store-url': 'https://www.drogeria-ekologiczna.pl/',
	},
	{
		'store-id': 'wieluszki',
		'store-name': 'Wieluszki',
		'store-src': 'wieluszki.jpeg',
		'store-brands': [ 'anavy', 'sue-and-sophie', 'kokosi', 'za-maszyna', 'magabi', 'zufizo', 'green-pieluszki', 'pupus', 'xkko', 'jellyfish', 'green-pieluszki', 'zufizo', 'fomi', 'anna-luna', 'doodush', 'rasppies', 'timi', 'tulipoopka', 'bambino-mio' ],
		'store-url': 'https://wieluszki.pl/',
	},
	{
		'store-id': 'blabla',
		'store-name': 'blabla',
		'store-src': 'wieluszki.jpeg',
		'store-brands': [ 'anavy', 'sue-and-sophie', 'kokosi', 'za-maszyna', 'magabi', 'zufizo', 'green-pieluszki', 'pupus', 'xkko', 'jellyfish', 'green-pieluszki', 'zufizo', 'fomi', 'anna-luna', 'doodush', 'rasppies', 'timi', 'tulipoopka', 'bambino-mio' ],
		'store-url': 'https://wieluszki.pl/',
	},
	{
		'store-id': 'aaaa',
		'store-name': 'aaaaa',
		'store-src': 'wieluszki.jpeg',
		'store-brands': [ 'anavy', 'sue-and-sophie', 'kokosi', 'za-maszyna', 'magabi', 'zufizo', 'green-pieluszki', 'pupus', 'xkko', 'jellyfish', 'green-pieluszki', 'zufizo', 'fomi', 'anna-luna', 'doodush', 'rasppies', 'timi', 'tulipoopka', 'bambino-mio' ],
		'store-url': 'https://wieluszki.pl/',
	},
	{
		'store-id': 'yyyyy',
		'store-name': 'yyyyy',
		'store-src': 'better-land.jpeg',
		'store-brands': [ 'anavy', 'sue-and-sophie', 'kokosi', 'lbd', 'puppi', 'magabi', 'disana', 'za-maszyna', 'magabi', 'zufizo', 'green-pieluszki', 'pupus', 'xkko', 'jellyfish', 'green-pieluszki', 'zufizo', 'baby-lemur', 'funky-monkey', 'little-rhino', 'fomi', 'anna-luna', 'funky-monkey',],
		'store-url': 'https://www.drogeria-ekologiczna.pl/',
	},
	{
		'store-id': 'cccc',
		'store-name': 'ccccccc',
		'store-src': 'chmurka-biala.png',
		'store-brands': [ 'kokosi', 'lbd', 'puppi', 'pupus', 'xkko', 'jellyfish', 'green-pieluszki', 'zufizo', 'rasppies', 'timi', 'tulipoopka', 'bambino-mio', 'latki-dwie', 'anavy', 'baby-lemur', 'funky-monkey', 'little-rhino' ],
		'store-url': 'https://chmurkabiala.pl/',
	},
	{
		'store-id': 'ddd',
		'store-name': 'ddd',
		'store-src': 'chmurka-biala.png',
		'store-brands': [ 'kokosi', 'lbd', 'puppi', 'pupus', 'xkko', 'jellyfish', 'green-pieluszki', 'zufizo', 'rasppies', 'timi', 'tulipoopka', 'bambino-mio', 'latki-dwie', 'anavy', 'baby-lemur', 'funky-monkey', 'little-rhino' ],
		'store-url': 'https://chmurkabiala.pl/',
	},
	{
		'store-id': 'fff',
		'store-name': 'fff',
		'store-src': 'chmurka-biala.png',
		'store-brands': [ 'kokosi', 'lbd', 'puppi', 'pupus', 'xkko', 'jellyfish', 'green-pieluszki', 'zufizo', 'rasppies', 'timi', 'tulipoopka', 'bambino-mio', 'latki-dwie', 'anavy', 'baby-lemur', 'funky-monkey', 'little-rhino' ],
		'store-url': 'https://chmurkabiala.pl/',
	},
	{
		'store-id': 'hhh',
		'store-name': 'hhh',
		'store-src': 'chmurka-biala.png',
		'store-brands': [ 'kokosi', 'lbd', 'puppi', 'pupus', 'xkko', 'jellyfish', 'green-pieluszki', 'zufizo', 'rasppies', 'timi', 'tulipoopka', 'bambino-mio', 'latki-dwie', 'anavy', 'baby-lemur', 'funky-monkey', 'little-rhino' ],
		'store-url': 'https://chmurkabiala.pl/',
	},
	{
		'store-id': 'jjjj',
		'store-name': 'jjj',
		'store-src': 'chmurka-biala.png',
		'store-brands': [ 'kokosi', 'lbd', 'puppi', 'pupus', 'xkko', 'jellyfish', 'green-pieluszki', 'zufizo', 'rasppies', 'timi', 'tulipoopka', 'bambino-mio', 'latki-dwie', 'anavy', 'baby-lemur', 'funky-monkey', 'little-rhino' ],
		'store-url': 'https://chmurkabiala.pl/',
	},
	{
		'store-id': 'kkk',
		'store-name': 'kkk',
		'store-src': 'chmurka-biala.png',
		'store-brands': [ 'kokosi', 'lbd', 'puppi', 'pupus', 'xkko', 'jellyfish', 'green-pieluszki', 'zufizo', 'rasppies', 'timi', 'tulipoopka', 'bambino-mio', 'latki-dwie', 'anavy', 'baby-lemur', 'funky-monkey', 'little-rhino' ],
		'store-url': 'https://chmurkabiala.pl/',
	},
	{
		'store-id': 'ooo',
		'store-name': 'ppp',
		'store-src': 'chmurka-biala.png',
		'store-brands': [ 'kokosi', 'lbd', 'puppi', 'pupus', 'xkko', 'jellyfish', 'green-pieluszki', 'zufizo', 'rasppies', 'timi', 'tulipoopka', 'bambino-mio', 'latki-dwie', 'anavy', 'baby-lemur', 'funky-monkey', 'little-rhino' ],
		'store-url': 'https://chmurkabiala.pl/',
	},
	{
		'store-id': 'ppp',
		'store-name': 'ppp',
		'store-src': 'chmurka-biala.png',
		'store-brands': [ 'kokosi', 'lbd', 'puppi', 'pupus', 'xkko', 'jellyfish', 'green-pieluszki', 'zufizo', 'rasppies', 'timi', 'tulipoopka', 'bambino-mio', 'latki-dwie', 'anavy', 'baby-lemur', 'funky-monkey', 'little-rhino' ],
		'store-url': 'https://chmurkabiala.pl/',
	},
	{
		'store-id': 'naturalnie-dla-dziecka',
		'store-name': 'Naturalnie dla Dziecka',
		'store-src': 'naturalnie-dla-dziecka.png',
		'store-brands': [ 'kokosi', 'lbd', 'puppi', 'pupus', 'xkko', 'jellyfish', 'green-pieluszki', 'zufizo', 'rasppies', 'timi', 'tulipoopka', 'bambino-mio', 'latki-dwie', 'anavy', 'baby-lemur', 'funky-monkey', 'little-rhino' ],
		'store-url': 'https://naturalniedladziecka.pl/',
	},
]